In [1]:
import torch
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt


In [26]:
data = pd.read_csv("/Users/guruiqin/deep-ml/data/california-house-price/housing_train.csv")
data = data.fillna(0)
data.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -116.46     33.82                 6.0       4863.0           920.0   
1    -117.04     34.00                21.0       4624.0           852.0   
2    -121.03     37.55                32.0        946.0           198.0   
3    -117.80     33.68                 8.0       2032.0           349.0   
4    -122.26     37.83                52.0       1656.0           420.0   

   population  households  median_income  median_house_value ocean_proximity  
0      3010.0       828.0         3.9508            104200.0          INLAND  
1      2174.0       812.0         3.5255            132100.0          INLAND  
2       624.0       173.0         1.9728             97900.0          INLAND  
3       862.0       340.0         6.9133            274100.0       <1H OCEAN  
4       718.0       382.0         2.6768            182300.0        NEAR BAY

In [27]:
train_data = data.drop(columns=['median_house_value'])
train_data.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -116.46     33.82                 6.0       4863.0           920.0   
1    -117.04     34.00                21.0       4624.0           852.0   
2    -121.03     37.55                32.0        946.0           198.0   
3    -117.80     33.68                 8.0       2032.0           349.0   
4    -122.26     37.83                52.0       1656.0           420.0   

   population  households  median_income ocean_proximity  
0      3010.0       828.0         3.9508          INLAND  
1      2174.0       812.0         3.5255          INLAND  
2       624.0       173.0         1.9728          INLAND  
3       862.0       340.0         6.9133       <1H OCEAN  
4       718.0       382.0         2.6768        NEAR BAY

In [28]:
y_data = data['median_house_value']
y_data.head(5)

0    104200.0
1    132100.0
2     97900.0
3    274100.0
4    182300.0
Name: median_house_value, dtype: float64

In [29]:
# 针对数值类特征 归一化  X - X.mean() / X.std()
for col in train_data.columns:
    # print(train_data[col].dtype)
    if (train_data[col].dtype == "float64"):
        X = train_data[col]
        # print("mean===>",X.mean())
        # print("max===>",X.std())
        X = (X-X.mean())/X.std()
        train_data[col] = X
train_data.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0   1.553894 -0.848357           -1.796989     0.997068        0.896706   
1   1.264659 -0.764112           -0.602216     0.889201        0.737748   
2  -0.725081  0.897404            0.273951    -0.770776       -0.791055   
3   0.885661 -0.913882           -1.637686    -0.280636       -0.438074   
4  -1.338460  1.028453            1.866982    -0.450334       -0.272103   

   population  households  median_income ocean_proximity  
0    1.409831    0.841409       0.039081          INLAND  
1    0.661270    0.799994      -0.184581          INLAND  
2   -0.726612   -0.854023      -1.001135          INLAND  
3   -0.513505   -0.421753       1.597040       <1H OCEAN  
4   -0.642444   -0.313038      -0.630907        NEAR BAY

In [30]:
# one-hot 一下这里简单写下
one_hot_data = pd.get_dummies( train_data['ocean_proximity'])
train_data = train_data.drop(columns=['ocean_proximity'])
train_data = pd.concat([train_data, one_hot_data],axis=1)
train_data.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0   1.553894 -0.848357           -1.796989     0.997068        0.896706   
1   1.264659 -0.764112           -0.602216     0.889201        0.737748   
2  -0.725081  0.897404            0.273951    -0.770776       -0.791055   
3   0.885661 -0.913882           -1.637686    -0.280636       -0.438074   
4  -1.338460  1.028453            1.866982    -0.450334       -0.272103   

   population  households  median_income  <1H OCEAN  INLAND  ISLAND  NEAR BAY  \
0    1.409831    0.841409       0.039081          0       1       0         0   
1    0.661270    0.799994      -0.184581          0       1       0         0   
2   -0.726612   -0.854023      -1.001135          0       1       0         0   
3   -0.513505   -0.421753       1.597040          1       0       0         0   
4   -0.642444   -0.313038      -0.630907          0       0       0         1   

   NEAR OCEAN  
0           0  
1           0  
2           0  
3           0  
4           0

In [7]:
# 如上步骤 针对值类型特征 归一化
# 针对枚举类特征  one-hot 处理了下

In [43]:
train_data.to_numpy().shape[1:]

(13,)

In [60]:
from tensorflow import keras
model = keras.models.Sequential(
	[    
		keras.layers.Dense(30, activation="relu", input_shape=train_data.to_numpy().shape[1:]),
		keras.layers.Dense(1)
	]
)
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 30)                420       
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 31        
Total params: 451
Trainable params: 451
Non-trainable params: 0
_________________________________________________________________


In [51]:
train_data.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0   1.553894 -0.848357           -1.796989     0.997068        0.896706   
1   1.264659 -0.764112           -0.602216     0.889201        0.737748   
2  -0.725081  0.897404            0.273951    -0.770776       -0.791055   
3   0.885661 -0.913882           -1.637686    -0.280636       -0.438074   
4  -1.338460  1.028453            1.866982    -0.450334       -0.272103   

   population  households  median_income  <1H OCEAN  INLAND  ISLAND  NEAR BAY  \
0    1.409831    0.841409       0.039081          0       1       0         0   
1    0.661270    0.799994      -0.184581          0       1       0         0   
2   -0.726612   -0.854023      -1.001135          0       1       0         0   
3   -0.513505   -0.421753       1.597040          1       0       0         0   
4   -0.642444   -0.313038      -0.630907          0       0       0         1   

   NEAR OCEAN  
0           0  
1           0  
2           0  
3           0  
4           0

In [58]:
X_train = train_data.to_numpy()
Y_train = y_data.to_numpy()
Y_train = (Y_train - Y_train.min()) / (Y_train.max() - Y_train.min())
print(X_train.shape)
print(X_train[:1])
print(Y_train[:1])

(14448, 13)
[[ 1.55389449 -0.84835745 -1.79698939  0.99706829  0.89670577  1.40983108
   0.8414092   0.03908122  0.          1.          0.          0.
   0.        ]]
[0.18391883]


In [61]:
print(X_train[:1].shape)
model.predict(X_train[:1])

(1, 13)


array([[-0.7058879]], dtype=float32)

In [63]:

model.compile(loss="mean_squared_error", optimizer="sgd")
# epochs 改小一点
model.fit(X_train, Y_train, epochs=5)

Epoch 1/50
452/452 [==============================] - 1s 1ms/step - loss: 0.0196
Epoch 2/50
452/452 [==============================] - 0s 1ms/step - loss: 0.0193
Epoch 3/50
452/452 [==============================] - 0s 887us/step - loss: 0.0190
Epoch 4/50
452/452 [==============================] - 0s 906us/step - loss: 0.0188
Epoch 5/50
452/452 [==============================] - 0s 861us/step - loss: 0.0186
Epoch 6/50
452/452 [==============================] - 0s 842us/step - loss: 0.0184
Epoch 7/50
452/452 [==============================] - 0s 896us/step - loss: 0.0183
Epoch 8/50
452/452 [==============================] - 0s 1ms/step - loss: 0.0182
Epoch 9/50
452/452 [==============================] - 1s 1ms/step - loss: 0.0181
Epoch 10/50
452/452 [==============================] - 0s 1ms/step - loss: 0.0180
Epoch 11/50
452/452 [==============================] - 0s 950us/step - loss: 0.0179
Epoch 12/50
452/452 [==============================] - 0s 900us/step - loss: 0.0178
Epoch 13/50

In [66]:
model.predict(X_train[:3])

array([[0.17509848],
       [0.21800932],
       [0.15500005]], dtype=float32)

In [68]:
Y_train[:3]

array([0.18391883, 0.24144437, 0.17092919])